#!/bin/bash

# Load .env function (if necessary)
loadEnv() {
  (set -a && . "${directory}/.env" && "$@")
}

# Reload Nginx and Apache containers gracefully
reload_http_containers() {
  # Reload Nginx
  if [ "$(docker ps -q -f name=NGINX)" ]; then
    echo -e "${GREEN}- Reloading Nginx container (NGINX)...${NC}"
    docker exec -it NGINX nginx -s reload
  fi

  # Gracefully reload Apache
  if [ "$(docker ps -q -f name=APACHE)" ]; then
    echo -e "${GREEN}- Gracefully reloading Apache container (APACHE)...${NC}"
    docker exec -it APACHE apachectl graceful
  fi
}

# Check for the existence of necessary files
check_file_existence() {
  local files=("$@")

  for file in "${files[@]}"; do
    local full_path="${directory}${file}"

    if [ ! -f "$full_path" ]; then
      echo -e "${RED}- Error: $full_path file is missing! Aborting.${NC}"
      exit 1
    fi
  done
}

# Update or insert a variable in the .env file
update_env() {
  local env_file="${directory}$1" # Prepend $directory to the provided env_file path
  local var_name="$2"
  local var_value="$3"

  if grep -qF "${var_name}=" "$env_file"; then
    local existing="$(grep "${var_name}=" "$env_file" | cut -d '=' -f 2)"
    if [ -z "$existing" ]; then
      sed -i "s|${var_name}=.*|${var_name}=${var_value}|" "$env_file"
      echo -e "${GREEN}- Updated ${var_name} in $env_file.${NC}"
    fi
  else
    echo -e "\n${var_name}=${var_value}" >>"$env_file"
    echo -e "${GREEN}- Added ${var_name} to $env_file.${NC}"
  fi
}

# Ensure necessary files exist, creating them if they don't
ensure_files_exist() {
  local files=("$@")

  for file in "${files[@]}"; do
    local full_path="${directory}${file}"
    local dir
    dir=$(dirname "$full_path")

    if [ ! -d "$dir" ]; then
      echo -e "${YELLOW}- Creating directory $dir.${NC}"
      mkdir -p "$dir"
    fi

    if [ ! -f "$full_path" ]; then
      echo -e "${YELLOW}- Creating file $full_path.${NC}"
      touch "$full_path"
    fi
  done
}

# Copy files while optionally excluding specific patterns
copy_files() {
  local full_source="${directory}$1"
  local full_destination="${directory}$2"
  local exclude_pattern="${4:-}"

  if [ ! -d "$full_destination" ]; then
    echo -e "${YELLOW}- Creating directory $full_destination for copying files.${NC}"
    mkdir -p "$full_destination"
  fi

  if [ -n "$exclude_pattern" ]; then
    find "$full_source" -type f -name "$3" ! -name "$exclude_pattern" -exec cp -ua {} "$full_destination" \;
  else
    find "$full_source" -type f -name "$3" -exec cp -ua {} "$full_destination" \;
  fi
}

# Wrapper for docker compose command
docker_compose() {
  docker compose --project-directory "$directory" -f "$directory/docker/compose/main.yaml" --env-file "$directory/docker/.env" "$@"
}

# Function to assign the correct permissions
assign_permissions() {

  if [[ "$(uname -s)" == *NT* || "$(uname -o)" == *Msys* || "$(uname -o)" == *Cygwin* ]]; then
    return
  fi

  # Set global permission on the $directory
  if [ "$(stat -c "%a" "$directory")" != "755" ]; then
    chmod 755 "$directory"
  fi

  if [ "$(stat -c "%a" "$directory/configuration/")" != "775" ]; then
    chmod 775 "$directory/configuration/"
  fi
  find "$directory/configuration/" -type f ! -perm 664 -exec chmod 664 {} \;
  chmod g+s "$directory/configuration/"

  if [ "$(stat -c "%a" "$directory/docker/")" != "755" ]; then
    chmod 755 "$directory/docker/"
  fi
  find "$directory/docker/" -type f ! -perm 644 -exec chmod 644 {} \;
  find "$directory/docker/conf/scripts/" -type f ! -perm 755 -exec chmod 755 {} \;

  if [ "$(stat -c "%a" "$directory/data/")" != "775" ]; then
    chmod 775 "$directory/data/"
  fi
  find "$directory/data/" -type f ! -perm 660 -exec chmod 660 {} \;
  chmod g+s "$directory/data/"
  chown -R "$USER:docker" "$directory/data/"

  if [ "$(stat -c "%a" "$directory/logs/")" != "775" ]; then
    chmod 775 "$directory/logs/"
  fi
  find "$directory/logs/" -type f ! -perm 660 -exec chmod 660 {} \;
  chmod g+s "$directory/logs/"
  chown -R "$USER:docker" "$directory/logs/"

  if [ "$(stat -c "%a" "$directory/bin/")" != "755" ]; then
    chmod 755 "$directory/bin/"
  fi
  find "$directory/bin/" -type f ! -perm 744 -exec chmod 744 {} \;

  if [ "$(stat -c "%a" "$directory/server")" != "744" ]; then
    chmod 744 "$directory/server"
  fi

  if [ "$(stat -c "%a" "$directory/setup")" != "744" ]; then
    chmod 744 "$directory/setup"
  fi
}