x-base-service: &default-service
  environment:
    - TZ=${TZ:-}
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro

services:
  # Single-Node Elasticsearch
  elasticsearch-server:
    <<: *default-service
    container_name: ELASTICSEARCH_SINGLE_NODE
    image: elasticsearch:${ELASTICSEARCH_VERSION:-8.12.2}
    profiles:
      - elasticsearch
    restart: always
    ports:
      - "${ELASTICSEARCH_PORT:-9200}:9200"
    environment:
      - "discovery.type=single-node"  # Single-node configuration
      - "xpack.security.enabled=false"
      - "cluster.name=single_node_cluster"
      - "node.name=elasticsearch-node-single"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      backend:
        ipv4_address: 172.23.1.1  # Static IP for single-node Elasticsearch
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Clustered Elasticsearch Node 1
  elasticsearch-cluster-node1:
    <<: *default-service
    container_name: ELASTICSEARCH_CLUSTER_NODE1
    image: elasticsearch:${ELASTICSEARCH_VERSION:-8.12.2}
    profiles:
      - elasticsearch-cluster
    restart: always
    environment:
      - "discovery.seed_hosts=elasticsearch-cluster-node1,elasticsearch-cluster-node2"
      - "cluster.initial_master_nodes=elasticsearch-cluster-node1,elasticsearch-cluster-node2"
      - "cluster.routing.allocation.awareness.attributes=rack_id"
      - "node.attr.rack_id=rack_one"
      - "cluster.name=my_elasticsearch_cluster"
      - "node.name=elasticsearch-node-1"
      - "ELASTICSEARCH_NUMBER_OF_SHARDS=${ELASTICSEARCH_NUMBER_OF_SHARDS:-3}"
      - "ELASTICSEARCH_NUMBER_OF_REPLICAS=${ELASTICSEARCH_NUMBER_OF_REPLICAS:-1}"
    volumes:
      - ./data/elasticsearch-node1:/usr/share/elasticsearch/data
    networks:
      backend:
        ipv4_address: 172.23.1.2  # Static IP for Elasticsearch Cluster Node 1
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Clustered Elasticsearch Node 2
  elasticsearch-cluster-node2:
    <<: *default-service
    container_name: ELASTICSEARCH_CLUSTER_NODE2
    image: elasticsearch:${ELASTICSEARCH_VERSION:-8.12.2}
    profiles:
      - elasticsearch-cluster
    restart: always
    environment:
      - "discovery.seed_hosts=elasticsearch-cluster-node1,elasticsearch-cluster-node2"
      - "cluster.initial_master_nodes=elasticsearch-cluster-node1,elasticsearch-cluster-node2"
      - "cluster.routing.allocation.awareness.attributes=rack_id"
      - "node.attr.rack_id=rack_two"
      - "cluster.name=my_elasticsearch_cluster"
      - "node.name=elasticsearch-node-2"
      - "ELASTICSEARCH_NUMBER_OF_SHARDS=${ELASTICSEARCH_NUMBER_OF_SHARDS:-3}"
      - "ELASTICSEARCH_NUMBER_OF_REPLICAS=${ELASTICSEARCH_NUMBER_OF_REPLICAS:-1}"
    volumes:
      - ./data/elasticsearch-node2:/usr/share/elasticsearch/data
    networks:
      backend:
        ipv4_address: 172.23.1.3  # Static IP for Elasticsearch Cluster Node 2
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Kibana Client
  elasticsearch-client:
    <<: *default-service
    container_name: KIBANA
    image: kibana:${ELASTICSEARCH_VERSION:-8.12.2}
    restart: always
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch-server:9200"
    depends_on:
      - elasticsearch-server
    volumes:
      - ./data/kibana-client:/usr/share/kibana/data
    networks:
      frontend:
        ipv4_address: 172.22.1.1  # Static IP for Kibana on Frontend
      backend:
        ipv4_address: 172.23.1.100  # Static IP for Kibana on Backend
    profiles:
      - kibana
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Kibana Client
  elasticsearch-cluster-client:
    <<: *default-service
    container_name: KIBANA_CLUSTER
    image: kibana:${ELASTICSEARCH_VERSION:-8.12.2}
    restart: always
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch-cluster-node1:9200"
    depends_on:
      - elasticsearch-cluster-node1
    volumes:
      - ./data/kibana-cluster:/usr/share/kibana/data
    networks:
      frontend:
        ipv4_address: 172.22.1.2  # Static IP for Kibana on Frontend
      backend:
        ipv4_address: 172.23.1.101  # Static IP for Kibana on Backend
    profiles:
      - kibana-cluster
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
