services:
  # Single-Node MongoDB
  mongo-server:
    container_name: MONGODB_SINGLE_NODE
    image: mongo:${MONGODB_VERSION:-latest}
    profiles:
      - mongodb
    restart: always
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD:-12345}
      - TZ=${TZ:-Asia/Dhaka}
    volumes:
      - ./data/mongo:/data/db
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # MongoDB Primary (Replica Set)
  mongo-primary:
    container_name: MONGODB_PRIMARY
    image: mongo:${MONGODB_VERSION:-latest}
    profiles:
      - mongodb-replica
    restart: always
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD:-12345}
      - TZ=${TZ:-Asia/Dhaka}
      - "MONGO_REPLICA_SET_NAME=rs0"
    volumes:
      - ./data/mongo-primary:/data/db
      - ./docker/conf/docker-files/scripts/mongo-replica:/scripts/init-replica.sh
    command: "--replSet rs0"
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 10s
      retries: 3
    entrypoint: [ "sh", "-c", "docker-entrypoint.sh --replSet rs0 && /scripts/init-replica.sh" ]

  # MongoDB Secondary 1
  mongo-secondary1:
    container_name: MONGODB_SECONDARY_1
    image: mongo:${MONGODB_VERSION:-latest}
    profiles:
      - mongodb-replica
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD:-12345}
      - TZ=${TZ:-Asia/Dhaka}
      - "MONGO_REPLICA_SET_NAME=rs0"
    volumes:
      - ./data/mongo-secondary1:/data/db
    command: "--replSet rs0"
    depends_on:
      - mongo-primary
    networks:
      - backend

  # MongoDB Secondary 2
  mongo-secondary2:
    container_name: MONGODB_SECONDARY_2
    image: mongo:${MONGODB_VERSION:-latest}
    profiles:
      - mongodb-replica
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD:-12345}
      - TZ=${TZ:-Asia/Dhaka}
      - "MONGO_REPLICA_SET_NAME=rs0"
    volumes:
      - ./data/mongo-secondary2:/data/db
    command: "--replSet rs0"
    depends_on:
      - mongo-primary
    networks:
      - backend

  # Mongo Express Client
  mongo-client:
    container_name: MONGO_ADMIN
    image: mongo-express:${ME_VERSION:-latest}
    restart: always
    ports:
      - "${ME_PORT:-8081}:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_BA_USERNAME:-root}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_BA_PASSWORD:-12345}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_ROOT_USERNAME:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_ROOT_PASSWORD:-12345}
      - TZ=${TZ:-Asia/Dhaka}
    networks:
      - frontend
      - backend
    profiles:
      mongodb:
        environment:
          - ME_CONFIG_MONGODB_URL=mongodb://${MONGODB_ROOT_USERNAME:-root}:${MONGODB_ROOT_PASSWORD:-12345}@mongo-server:${MONGODB_PORT:-27017}/
      mongodb-replica:
        environment:
          - ME_CONFIG_MONGODB_URL=mongodb://${MONGODB_ROOT_USERNAME:-root}:${MONGODB_ROOT_PASSWORD:-12345}@mongo-primary:${MONGODB_PORT:-27017}/?replicaSet=rs0
