services:
  # MySQL Single Instance
  mysql-single:
    container_name: MYSQL_SINGLE
    image: mysql:${MYSQL_VERSION:-latest}
    profiles:
      - mysql
    restart: always
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-12345}
      - MYSQL_USER=${MYSQL_USER:-devuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-12345}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-localdb}
      - TZ=${TZ:-Asia/Dhaka}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    networks:
      backend:
        ipv4_address: 172.23.4.0  # Static IP for MySQL Single Instance
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MariaDB Single Instance
  mariadb-single:
    container_name: MARIADB_SINGLE
    image: mariadb:${MARIADB_VERSION:-latest}
    profiles:
      - mariadb
    restart: always
    ports:
      - "${MARIADB_PORT:-3306}:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-12345}
      - MARIADB_USER=${MARIADB_USER:-devuser}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-12345}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-localdb}
      - TZ=${TZ:-Asia/Dhaka}
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./logs/mariadb:/var/log/mysql
    networks:
      backend:
        ipv4_address: 172.23.4.1  # Static IP for MariaDB Single Instance
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MySQL Master (Primary)
  mysql-master:
    container_name: MYSQL_MASTER
    image: mysql:${MYSQL_VERSION:-latest}
    profiles:
      - mysql-replication
    restart: always
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-12345}
      - MYSQL_USER=${MYSQL_USER:-devuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-12345}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-localdb}
      - MYSQL_REPLICATION_USER=${MYSQL_REPLICATION_USER:-replicauser}
      - MYSQL_REPLICATION_PASSWORD=${MYSQL_REPLICATION_PASSWORD:-replpassword}
      - TZ=${TZ:-Asia/Dhaka}
    volumes:
      - ./data/mysql-master:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    networks:
      backend:
        ipv4_address: 172.23.4.2  # Static IP for MySQL Master
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    command:
      --log-bin=mysql-bin
      --server-id=1

  # MySQL Slave (Replica)
  mysql-slave:
    container_name: MYSQL_SLAVE
    image: mysql:${MYSQL_VERSION:-latest}
    profiles:
      - mysql-replication
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-12345}
      - MYSQL_USER=${MYSQL_USER:-devuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-12345}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-localdb}
      - MYSQL_REPLICATION_USER=${MYSQL_REPLICATION_USER:-replicauser}
      - MYSQL_REPLICATION_PASSWORD=${MYSQL_REPLICATION_PASSWORD:-replpassword}
      - TZ=${TZ:-Asia/Dhaka}
    volumes:
      - ./data/mysql-slave:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    networks:
      backend:
        ipv4_address: 172.23.4.3  # Static IP for MySQL Slave
    depends_on:
      - mysql-master
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    command:
      --server-id=2
    entrypoint: [ "sh", "-c", "
      mysql -u root -p${MYSQL_ROOT_PASSWORD} -e \"
        STOP SLAVE;
        CHANGE MASTER TO MASTER_HOST='mysql-master', MASTER_USER='${MYSQL_REPLICATION_USER}', MASTER_PASSWORD='${MYSQL_REPLICATION_PASSWORD}', MASTER_LOG_FILE='mysql-bin.000001', MASTER_LOG_POS=0;
        START SLAVE;
      \"
    "]

  # MariaDB Master (Primary)
  mariadb-master:
    container_name: MARIADB_MASTER
    image: mariadb:${MARIADB_VERSION:-latest}
    profiles:
      - mariadb-replication
    restart: always
    ports:
      - "${MARIADB_PORT:-3306}:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-12345}
      - MARIADB_USER=${MARIADB_USER:-devuser}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-12345}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-localdb}
      - MARIADB_REPLICATION_USER=${MARIADB_REPLICATION_USER:-replicauser}
      - MARIADB_REPLICATION_PASSWORD=${MARIADB_REPLICATION_PASSWORD:-replpassword}
      - TZ=${TZ:-Asia/Dhaka}
    volumes:
      - ./data/mariadb-master:/var/lib/mysql
      - ./logs/mariadb:/var/log/mysql
    networks:
      backend:
        ipv4_address: 172.23.4.4  # Static IP for MariaDB Master
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    command:
      --log-bin=mysql-bin
      --server-id=1

  # MariaDB Slave (Replica)
  mariadb-slave:
    container_name: MARIADB_SLAVE
    image: mariadb:${MARIADB_VERSION:-latest}
    profiles:
      - mariadb-replication
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-12345}
      - MARIADB_USER=${MARIADB_USER:-devuser}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-12345}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-localdb}
      - MARIADB_REPLICATION_USER=${MARIADB_REPLICATION_USER:-replicauser}
      - MARIADB_REPLICATION_PASSWORD=${MARIADB_REPLICATION_PASSWORD:-replpassword}
      - TZ=${TZ:-Asia/Dhaka}
    volumes:
      - ./data/mariadb-slave:/var/lib/mysql
      - ./logs/mariadb:/var/log/mysql
    networks:
      backend:
        ipv4_address: 172.23.4.5  # Static IP for MariaDB Slave
    depends_on:
      - mariadb-master
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    command:
      --server-id=2
    entrypoint: [ "sh", "-c", "
      mysql -u root -p${MARIADB_ROOT_PASSWORD} -e \"
        STOP SLAVE;
        CHANGE MASTER TO MASTER_HOST='mariadb-master', MASTER_USER='${MARIADB_REPLICATION_USER}', MASTER_PASSWORD='${MARIADB_REPLICATION_PASSWORD}', MASTER_LOG_FILE='mysql-bin.000001', MASTER_LOG_POS=0;
        START SLAVE;
      \"
    "]

  # phpMyAdmin Client
  mysql-client:
    container_name: MY_ADMIN
    image: phpmyadmin:latest
    restart: always
    ports:
      - "${MYADMIN_PORT:-3300}:80"
    environment:
      - PMA_ARBITRARY=1
      - TZ=${TZ:-Asia/Dhaka}
      - PMA_PORT=${MYSQL_PORT:-3306}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-12345}
      - MYSQL_USER=${MYSQL_USER:-devuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-12345}
    volumes:
      - ./configuration/php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./data/phpmyadmin:/etc/phpmyadmin/conf.d:ro
    networks:
      frontend:
        ipv4_address: 172.22.4.0  # Static IP for phpMyAdmin on Frontend network
      backend:
        ipv4_address: 172.23.4.6  # Static IP for phpMyAdmin on Backend network
    profiles:
      mysql:
        PMA_HOST: mysql-single
      mysql-replication:
        PMA_HOST: mysql-master
      mariadb:
        PMA_HOST: mariadb-single
      mariadb-replication:
        PMA_HOST: mariadb-master
