x-base-service: &default-service
  environment:
    - TZ=${TZ:-}
  networks:
    - datastore
  healthcheck:
    test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
    interval: 30s
    timeout: 10s
    retries: 3

services:
  mysql-single:
    <<: *default-service
    container_name: MYSQL_SINGLE
    hostname: mysql-single
    image: mysql:${MYSQL_VERSION:-latest}
    profiles:
      - mysql
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-12345}
      - MYSQL_USER=${MYSQL_USER:-devuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-12345}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-localdb}
    volumes:
      - ../../data/mysql-single:/var/lib/mysql
      - ../../logs/mysql-single:/var/log/mysql

  # MySQL Master (Primary) for replication
  mysql-master:
    <<: *default-service
    container_name: MYSQL_MASTER
    hostname: mysql-master
    image: mysql:${MYSQL_VERSION:-latest}
    profiles:
      - mysql-replication
    restart: unless-stopped
    ports:
      - "${MYSQL_MASTER_PORT:-3307}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-12345}
      - MYSQL_USER=${MYSQL_USER:-devuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-12345}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-localdb}
      - MYSQL_REPLICATION_USER=${MYSQL_REPLICATION_USER:-replicauser}
      - MYSQL_REPLICATION_PASSWORD=${MYSQL_REPLICATION_PASSWORD:-replpassword}
    volumes:
      - ../../data/mysql-master:/var/lib/mysql
      - ../../logs/mysql-master:/var/log/mysql
    command:
      - --log-bin=mysql-bin
      - --server-id=1

  # MySQL Slave (Replica)
  mysql-slave:
    <<: *default-service
    container_name: MYSQL_SLAVE
    hostname: mysql-slave
    image: mysql:${MYSQL_VERSION:-latest}
    profiles:
      - mysql-replication
    restart: unless-stopped
    depends_on:
      - mysql-master
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-12345}
      - MYSQL_USER=${MYSQL_USER:-devuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-12345}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-localdb}
      - MYSQL_REPLICATION_USER=${MYSQL_REPLICATION_USER:-replicauser}
      - MYSQL_REPLICATION_PASSWORD=${MYSQL_REPLICATION_PASSWORD:-replpassword}
    volumes:
      - ../../data/mysql-slave:/var/lib/mysql
      - ../../logs/mysql-slave:/var/log/mysql
      - ../conf/mysql-replicate.sh:/docker-entrypoint-initdb.d/replicate.sh:ro
    command:
      - --server-id=2

  # Unified DBeaver/CloudBeaver Client
  mysql-client:
    <<: *default-service
    container_name: MYSQL_CLIENT
    hostname: mysql-client
    image: dbeaver/cloudbeaver:latest
    profiles:
      - mysql-client
    restart: unless-stopped
    ports:
      - "${DBEAVER_PORT:-8080}:8978"
    environment:
      - CB_ADMIN_LOGIN=${MYSQL_CLIENT_USER:-admin}
      - CB_ADMIN_PASSWORD=${MYSQL_CLIENT_PASSWORD:-admin}
    volumes:
      - ../../data/dbeaver-mysql:/opt/cloudbeaver/workspace
    networks:
      - frontend
      - datastore
