services:
  # MySQL/MariaDB Single Instance
  mysql-single:
    container_name: MYSQL_SINGLE
    image: ${MYSQL_IMAGE:-mariadb}:${MYSQL_VERSION:-latest}
    profiles:
      - mysql
    restart: always
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-12345}
      - MYSQL_USER=${MYSQL_USER:-devuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-12345}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-localdb}
      - TZ=${TZ:-Asia/Dhaka}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MySQL Master (Primary)
  mysql-master:
    container_name: MYSQL_MASTER
    image: ${MYSQL_IMAGE:-mariadb}:${MYSQL_VERSION:-latest}
    profiles:
      - mysql-replication
    restart: always
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-12345}
      - MYSQL_USER=${MYSQL_USER:-devuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-12345}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-localdb}
      - MYSQL_REPLICATION_USER=${MYSQL_REPLICATION_USER:-replicauser}
      - MYSQL_REPLICATION_PASSWORD=${MYSQL_REPLICATION_PASSWORD:-replpassword}
      - TZ=${TZ:-Asia/Dhaka}
    volumes:
      - ./data/mysql-master:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    command:
      --log-bin=mysql-bin
      --server-id=1

  # MySQL Slave (Replica)
  mysql-slave:
    container_name: MYSQL_SLAVE
    image: ${MYSQL_IMAGE:-mariadb}:${MYSQL_VERSION:-latest}
    profiles:
      - mysql-replication
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-12345}
      - MYSQL_USER=${MYSQL_USER:-devuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-12345}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-localdb}
      - MYSQL_REPLICATION_USER=${MYSQL_REPLICATION_USER:-replicauser}
      - MYSQL_REPLICATION_PASSWORD=${MYSQL_REPLICATION_PASSWORD:-replpassword}
      - TZ=${TZ:-Asia/Dhaka}
    volumes:
      - ./data/mysql-slave:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    networks:
      - backend
    depends_on:
      - mysql-master
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    command:
      --server-id=2
    entrypoint: [ "sh", "-c", "
      mysql -u root -p${MYSQL_ROOT_PASSWORD} -e \"
        STOP SLAVE;
        CHANGE MASTER TO MASTER_HOST='mysql-master', MASTER_USER='${MYSQL_REPLICATION_USER}', MASTER_PASSWORD='${MYSQL_REPLICATION_PASSWORD}', MASTER_LOG_FILE='mysql-bin.000001', MASTER_LOG_POS=0;
        START SLAVE;
      \"
    "]

  # phpMyAdmin Client
  mysql-client:
    container_name: MY_ADMIN
    image: phpmyadmin:latest
    restart: always
    ports:
      - "${MYADMIN_PORT:-3300}:80"
    environment:
      - PMA_ARBITRARY=1
      - TZ=${TZ:-Asia/Dhaka}
    volumes:
      - ./configuration/php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./data/phpmyadmin:/etc/phpmyadmin/conf.d:ro
    networks:
      - frontend
      - backend
    profiles:
      mysql:
        environment:
          - PMA_HOST=mysql-single
          - PMA_PORT=${MYSQL_PORT:-3306}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-12345}
          - MYSQL_USER=${MYSQL_USER:-devuser}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD:-12345}
      mysql-replication:
        environment:
          - PMA_HOST=mysql-master
          - PMA_PORT=${MYSQL_PORT:-3306}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-12345}
          - MYSQL_USER=${MYSQL_USER:-devuser}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD:-12345}
