x-php-cli-service: &php-cli-service
  restart: unless-stopped
  environment:
    - TZ=${TZ:-}
  env_file:
    - "../../.env"
  networks:
    - backend
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - "${PROJECT_DIR:-./../../../application}:/app"
    - ../conf/openssl.cnf:/etc/ssl/openssl.cnf
    - ../../configuration/php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    - "../../configuration/ssh:/home/${USER}/.ssh:ro"
    - ../../configuration/scheduler:/etc/supervisor/conf.d:ro
  extra_hosts:
    - "host.docker.internal:host-gateway"
  depends_on:
    - server-tools

services:
  php74cli:
    <<: *php-cli-service
    container_name: PHP_7.4_CLI
    hostname: php-74-cli
    build:
      context: ../dockerfiles
      dockerfile: cli.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-root}
        USERNAME: ${USER}
        PHP_EXT: ${PHP_EXT:-}
        LINUX_PKG: ${LINUX_PKG:-}
        WORKING_DIR: ${WORKING_DIR}
        PHP_VERSION: 7.4
        PHP_EXT_VERSIONED: ${PHP_EXT_74:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_74:-}
    profiles:
      - php-cli
      - php74-cli

  php80cli:
    <<: *php-cli-service
    container_name: PHP_8.0_CLI
    hostname: php-80-cli
    build:
      context: ../dockerfiles
      dockerfile: cli.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-root}
        USERNAME: ${USER}
        PHP_EXT: ${PHP_EXT:-}
        LINUX_PKG: ${LINUX_PKG:-}
        NODE_VERSION: ${NODE_VERSION:-}
        WORKING_DIR: ${WORKING_DIR}
        PHP_VERSION: 8.0
        PHP_EXT_VERSIONED: ${PHP_EXT_80:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_80:-}
    profiles:
      - php-cli
      - php80-cli

  php81cli:
    <<: *php-cli-service
    container_name: PHP_8.1_CLI
    hostname: php-81-cli
    build:
      context: ../dockerfiles
      dockerfile: cli.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-root}
        USERNAME: ${USER}
        PHP_EXT: ${PHP_EXT:-}
        LINUX_PKG: ${LINUX_PKG:-}
        NODE_VERSION: ${NODE_VERSION:-}
        WORKING_DIR: ${WORKING_DIR}
        PHP_VERSION: 8.1
        PHP_EXT_VERSIONED: ${PHP_EXT_81:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_81:-}
    profiles:
      - php-cli
      - php81-cli

  php82cli:
    <<: *php-cli-service
    container_name: PHP_8.2_CLI
    hostname: php-82-cli
    build:
      context: ../dockerfiles
      dockerfile: cli.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-root}
        USERNAME: ${USER}
        PHP_EXT: ${PHP_EXT:-}
        LINUX_PKG: ${LINUX_PKG:-}
        NODE_VERSION: ${NODE_VERSION:-}
        WORKING_DIR: ${WORKING_DIR}
        PHP_VERSION: 8.2
        PHP_EXT_VERSIONED: ${PHP_EXT_82:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_82:-}
    profiles:
      - php-cli
      - php82-cli

  php83cli:
    <<: *php-cli-service
    container_name: PHP_8.3_CLI
    hostname: php-83-cli
    build:
      context: ../dockerfiles
      dockerfile: cli.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-root}
        USERNAME: ${USER}
        PHP_EXT: ${PHP_EXT:-}
        LINUX_PKG: ${LINUX_PKG:-}
        NODE_VERSION: ${NODE_VERSION:-}
        WORKING_DIR: ${WORKING_DIR}
        PHP_VERSION: 8.3
        PHP_EXT_VERSIONED: ${PHP_EXT_83:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_83:-}
    profiles:
      - php-cli
      - php83-cli

  php84cli:
    <<: *php-cli-service
    container_name: PHP_8.4_CLI
    hostname: php-84-cli
    build:
      context: ../dockerfiles
      dockerfile: cli.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-root}
        USERNAME: ${USER}
        PHP_EXT: ${PHP_EXT:-}
        LINUX_PKG: ${LINUX_PKG:-}
        NODE_VERSION: ${NODE_VERSION:-}
        WORKING_DIR: ${WORKING_DIR}
        PHP_VERSION: 8.4
        PHP_EXT_VERSIONED: ${PHP_EXT_84:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_84:-}
    profiles:
      - php-cli
      - php84-cli
