x-php-fpm-service: &php-fpm-service
  restart: unless-stopped
  environment:
    - TZ=${TZ:-}
  env_file:
    - "../../.env"
  networks:
    - frontend
    - backend
  volumes:
    - /etc/localtime:/etc/localtime
    - /etc/timezone:/etc/timezone
    - "${PROJECT_DIR:-./../../../application}:/app"
    - ../conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
    - ../conf/openssl.cnf:/etc/ssl/openssl.cnf
    - ../../configuration/php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    - "../../configuration/ssh:/home/${USER}/.ssh:ro"
  extra_hosts:
    - "host.docker.internal:host-gateway"
  depends_on:
    - server-tools
  healthcheck:
    test: ["CMD-SHELL", "php-fpm -t || exit 1"]
    interval: 30s
    timeout: 10s
    retries: 3

services:
  php74:
    <<: *php-fpm-service
    container_name: PHP_7.4
    hostname: php-74
    build:
      context: ../dockerfiles
      dockerfile: fpm.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USER}
        PHP_EXT: ${PHP_EXT:-}
        LINUX_PKG: ${LINUX_PKG:-}
        NODE_VERSION: ${NODE_VERSION:-}
        WORKING_DIR: ${WORKING_DIR}
        PHP_VERSION: 7.4
        PHP_EXT_VERSIONED: ${PHP_EXT_74:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_74:-}
        NODE_VERSION_VERSIONED: ${NODE_VERSION_74:-}
    profiles:
      - php
      - php74

  php80:
    <<: *php-fpm-service
    container_name: PHP_8.0
    hostname: php-80
    build:
      context: ../dockerfiles
      dockerfile: fpm.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USER}
        PHP_EXT: ${PHP_EXT:-}
        LINUX_PKG: ${LINUX_PKG:-}
        NODE_VERSION: ${NODE_VERSION:-}
        WORKING_DIR: ${WORKING_DIR}
        PHP_VERSION: 8.0
        PHP_EXT_VERSIONED: ${PHP_EXT_80:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_80:-}
        NODE_VERSION_VERSIONED: ${NODE_VERSION_80:-}
    profiles:
      - php
      - php80

  php81:
    <<: *php-fpm-service
    container_name: PHP_8.1
    hostname: php-81
    build:
      context: ../dockerfiles
      dockerfile: fpm.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USER}
        PHP_EXT: ${PHP_EXT:-}
        LINUX_PKG: ${LINUX_PKG:-}
        NODE_VERSION: ${NODE_VERSION:-}
        WORKING_DIR: ${WORKING_DIR}
        PHP_VERSION: 8.1
        PHP_EXT_VERSIONED: ${PHP_EXT_81:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_81:-}
        NODE_VERSION_VERSIONED: ${NODE_VERSION_81:-}
    profiles:
      - php
      - php81

  php82:
    <<: *php-fpm-service
    container_name: PHP_8.2
    hostname: php-82
    build:
      context: ../dockerfiles
      dockerfile: fpm.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USER}
        PHP_EXT: ${PHP_EXT:-}
        LINUX_PKG: ${LINUX_PKG:-}
        NODE_VERSION: ${NODE_VERSION:-}
        WORKING_DIR: ${WORKING_DIR}
        PHP_VERSION: 8.2
        PHP_EXT_VERSIONED: ${PHP_EXT_82:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_82:-}
        NODE_VERSION_VERSIONED: ${NODE_VERSION_82:-}
    profiles:
      - php
      - php82

  php83:
    <<: *php-fpm-service
    container_name: PHP_8.3
    hostname: php-83
    build:
      context: ../dockerfiles
      dockerfile: fpm.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USER}
        PHP_EXT: ${PHP_EXT:-}
        LINUX_PKG: ${LINUX_PKG:-}
        NODE_VERSION: ${NODE_VERSION:-}
        WORKING_DIR: ${WORKING_DIR}
        PHP_VERSION: 8.3
        PHP_EXT_VERSIONED: ${PHP_EXT_83:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_83:-}
        NODE_VERSION_VERSIONED: ${NODE_VERSION_83:-}
    profiles:
      - php
      - php83

  php84:
    <<: *php-fpm-service
    container_name: PHP_8.4
    hostname: php-84
    build:
      context: ../dockerfiles
      dockerfile: fpm.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USER}
        PHP_EXT: ${PHP_EXT:-}
        LINUX_PKG: ${LINUX_PKG:-}
        NODE_VERSION: ${NODE_VERSION:-}
        WORKING_DIR: ${WORKING_DIR}
        PHP_VERSION: 8.4
        PHP_EXT_VERSIONED: ${PHP_EXT_84:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_84:-}
        NODE_VERSION_VERSIONED: ${NODE_VERSION_84:-}
    profiles:
      - php
      - php84
