x-php-cli-service: &php-cli-service
  build:
    context: docker/conf/docker-files
    dockerfile: cli.Dockerfile
    args:
      UID: ${UID:-1000}
      GID: ${GID:-root}
      PHP_EXT: ${PHP_EXT:-}
      LINUX_PKG: ${LINUX_PKG:-}
      WORKING_DIR: ${WORKING_DIR}
  restart: always
  environment:
    - TZ=${TZ:-Asia/Dhaka}
  env_file:
    - "./.env"
  volumes:
    - "${PROJECT_DIR:-./../application}:/app"
    - ./configuration/php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    - ./docker/conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    - ./docker/conf/php/openssl.cnf:/etc/ssl/openssl.cnf
    - ./configuration/ssh:/home/devuser/.ssh
  extra_hosts:
    - "host.docker.internal:host-gateway"
  networks:
    backend:
      ipv4_address: 172.23.5.0  # Default IP range for backend network

services:
  php74cli:
    <<: *php-cli-service
    container_name: PHP_7.4_CLI
    build:
      args:
        PHP_VERSION: 7.4
        PHP_EXT_VERSIONED: ${PHP_EXT_74:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_74:-}
    networks:
      backend:
        ipv4_address: 172.23.5.1  # Static IP for PHP 7.4 CLI
    profiles:
      - php-cli
      - php74-cli

  php80cli:
    <<: *php-cli-service
    container_name: PHP_8.0_CLI
    build:
      args:
        PHP_VERSION: 8.0
        PHP_EXT_VERSIONED: ${PHP_EXT_80:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_80:-}
    networks:
      backend:
        ipv4_address: 172.23.5.2  # Static IP for PHP 8.0 CLI
    profiles:
      - php-cli
      - php80-cli

  php81cli:
    <<: *php-cli-service
    container_name: PHP_8.1_CLI
    build:
      args:
        PHP_VERSION: 8.1
        PHP_EXT_VERSIONED: ${PHP_EXT_81:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_81:-}
    networks:
      backend:
        ipv4_address: 172.23.5.3  # Static IP for PHP 8.1 CLI
    profiles:
      - php-cli
      - php81-cli

  php82cli:
    <<: *php-cli-service
    container_name: PHP_8.2_CLI
    build:
      args:
        PHP_VERSION: 8.2
        PHP_EXT_VERSIONED: ${PHP_EXT_82:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_82:-}
    networks:
      backend:
        ipv4_address: 172.23.5.4  # Static IP for PHP 8.2 CLI
    profiles:
      - php-cli
      - php82-cli

  php83cli:
    <<: *php-cli-service
    container_name: PHP_8.3_CLI
    build:
      args:
        PHP_VERSION: 8.3
        PHP_EXT_VERSIONED: ${PHP_EXT_83:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_83:-}
    networks:
      backend:
        ipv4_address: 172.23.5.5  # Static IP for PHP 8.3 CLI
    profiles:
      - php-cli
      - php83-cli

  php84cli:
    <<: *php-cli-service
    container_name: PHP_8.4_CLI
    build:
      args:
        PHP_VERSION: 8.4
        PHP_EXT_VERSIONED: ${PHP_EXT_84:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_84:-}
    networks:
      backend:
        ipv4_address: 172.23.5.6  # Static IP for PHP 8.4 CLI
    profiles:
      - php-cli
      - php84-cli
