x-php-service: &php-service
  build:
    context: docker/conf/docker-files
    dockerfile: fpm.Dockerfile
    args:
      UID: ${UID:-1000}
      GID: ${GID:-root}
      PHP_EXT: ${PHP_EXT:-}
      LINUX_PKG: ${LINUX_PKG:-}
      NODE_VERSION: ${NODE_VERSION:-}
      WORKING_DIR: ${WORKING_DIR}
  restart: always
  environment:
    - TZ=${TZ:-}
  env_file:
    - "./.env"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - "${PROJECT_DIR:-./../application}:/app"
    - ./configuration/php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    - ./docker/conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    - ./docker/conf/php/openssl.cnf:/etc/ssl/openssl.cnf
    - ./configuration/ssh:/home/devuser/.ssh
  extra_hosts:
    - "host.docker.internal:host-gateway"
  healthcheck:
    test: ["CMD-SHELL", "php-fpm -t || exit 1"]
    interval: 30s
    timeout: 10s
    retries: 3

services:
  php74:
    <<: *php-service
    container_name: PHP_7.4
    build:
      args:
        PHP_VERSION: 7.4
        PHP_EXT_VERSIONED: ${PHP_EXT_74:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_74:-}
        NODE_VERSION_VERSIONED: ${NODE_VERSION_74:-}
    networks:
      frontend:
        ipv4_address: 172.22.6.1  # Static IP for PHP 7.4 (Frontend)
      backend:
        ipv4_address: 172.23.6.1  # Static IP for PHP 7.4 (Backend)
    profiles:
      - php
      - php74

  php80:
    <<: *php-service
    container_name: PHP_8.0
    build:
      args:
        PHP_VERSION: 8.0
        PHP_EXT_VERSIONED: ${PHP_EXT_80:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_80:-}
        NODE_VERSION_VERSIONED: ${NODE_VERSION_80:-}
    networks:
      frontend:
        ipv4_address: 172.22.6.2  # Static IP for PHP 8.0 (Frontend)
      backend:
        ipv4_address: 172.23.6.2  # Static IP for PHP 8.0 (Backend)
    profiles:
      - php
      - php80

  php81:
    <<: *php-service
    container_name: PHP_8.1
    build:
      args:
        PHP_VERSION: 8.1
        PHP_EXT_VERSIONED: ${PHP_EXT_81:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_81:-}
        NODE_VERSION_VERSIONED: ${NODE_VERSION_81:-}
    networks:
      frontend:
        ipv4_address: 172.22.6.3  # Static IP for PHP 8.1 (Frontend)
      backend:
        ipv4_address: 172.23.6.3  # Static IP for PHP 8.1 (Backend)
    profiles:
      - php
      - php81

  php82:
    <<: *php-service
    container_name: PHP_8.2
    build:
      args:
        PHP_VERSION: 8.2
        PHP_EXT_VERSIONED: ${PHP_EXT_82:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_82:-}
        NODE_VERSION_VERSIONED: ${NODE_VERSION_82:-}
    networks:
      frontend:
        ipv4_address: 172.22.6.4  # Static IP for PHP 8.2 (Frontend)
      backend:
        ipv4_address: 172.23.6.4  # Static IP for PHP 8.2 (Backend)
    profiles:
      - php
      - php82

  php83:
    <<: *php-service
    container_name: PHP_8.3
    build:
      args:
        PHP_VERSION: 8.3
        PHP_EXT_VERSIONED: ${PHP_EXT_83:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_83:-}
        NODE_VERSION_VERSIONED: ${NODE_VERSION_83:-}
    networks:
      frontend:
        ipv4_address: 172.22.6.5  # Static IP for PHP 8.3 (Frontend)
      backend:
        ipv4_address: 172.23.6.5  # Static IP for PHP 8.3 (Backend)
    profiles:
      - php
      - php83

  php84:
    <<: *php-service
    container_name: PHP_8.4
    build:
      args:
        PHP_VERSION: 8.4
        PHP_EXT_VERSIONED: ${PHP_EXT_84:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_84:-}
        NODE_VERSION_VERSIONED: ${NODE_VERSION_84:-}
    networks:
      frontend:
        ipv4_address: 172.22.6.6  # Static IP for PHP 8.4 (Frontend)
      backend:
        ipv4_address: 172.23.6.6  # Static IP for PHP 8.4 (Backend)
    profiles:
      - php
      - php84
