x-apache-php-service: &apache-php-service
  restart: unless-stopped
  environment:
    - TZ=${TZ:-}
  env_file:
    - "../../.env"
  networks:
    - frontend
    - backend
  extra_hosts:
    - "host.docker.internal:host-gateway"
  depends_on:
    - server-tools
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost" ]
    interval: 30s
    timeout: 10s
    retries: 3

services:
  php73apache:
    <<: *apache-php-service
    container_name: PHP_7.3_APACHE
    hostname: php-73-apache
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - "${PROJECT_DIR:-./../../../application}:/app"
      - ../conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ../conf/openssl.cnf:/etc/ssl/openssl.cnf
      - ../../configuration/php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ../../configuration/apache/php73:/etc/apache2/sites-enabled
      - ../../configuration/ssl:/etc/mkcert
      - "../../configuration/ssh:/home/${USER}/.ssh:ro"
      - ../../logs/apache:/var/log/apache2
    build:
      context: ../dockerfiles
      dockerfile: apache.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USER}
        PHP_EXT: ${PHP_EXT:-}
        LINUX_PKG: ${LINUX_PKG:-}
        NODE_VERSION: ${NODE_VERSION:-}
        WORKING_DIR: ${WORKING_DIR}
        PHP_VERSION: 7.3
        PHP_EXT_VERSIONED: ${PHP_EXT_73:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_73:-}
        NODE_VERSION_VERSIONED: ${NODE_VERSION_73:-}
    profiles:
      - phpapache
      - php73apache
  
  php74apache:
    <<: *apache-php-service
    container_name: PHP_7.4_APACHE
    hostname: php-74-apache
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - "${PROJECT_DIR:-./../../../application}:/app"
      - ../conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ../conf/openssl.cnf:/etc/ssl/openssl.cnf
      - ../../configuration/php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ../../configuration/apache/php74:/etc/apache2/sites-enabled
      - ../../configuration/ssl:/etc/mkcert
      - "../../configuration/ssh:/home/${USER}/.ssh:ro"
      - ../../logs/apache:/var/log/apache2
    build:
      context: ../dockerfiles
      dockerfile: apache.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USER}
        PHP_EXT: ${PHP_EXT:-}
        LINUX_PKG: ${LINUX_PKG:-}
        NODE_VERSION: ${NODE_VERSION:-}
        WORKING_DIR: ${WORKING_DIR}
        PHP_VERSION: 7.4
        PHP_EXT_VERSIONED: ${PHP_EXT_74:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_74:-}
        NODE_VERSION_VERSIONED: ${NODE_VERSION_74:-}
    profiles:
      - phpapache
      - php74apache

  php80apache:
    <<: *apache-php-service
    container_name: PHP_8.0_APACHE
    hostname: php-80-apache
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - "${PROJECT_DIR:-./../../../application}:/app"
      - ../conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ../conf/openssl.cnf:/etc/ssl/openssl.cnf
      - ../../configuration/php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ../../configuration/apache/php80:/etc/apache2/sites-enabled
      - ../../configuration/ssl:/etc/mkcert
      - "../../configuration/ssh:/home/${USER}/.ssh:ro"
      - ../../logs/apache:/var/log/apache2
    build:
      context: ../dockerfiles
      dockerfile: apache.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USER}
        PHP_EXT: ${PHP_EXT:-}
        LINUX_PKG: ${LINUX_PKG:-}
        NODE_VERSION: ${NODE_VERSION:-}
        WORKING_DIR: ${WORKING_DIR}
        PHP_VERSION: 8.0
        PHP_EXT_VERSIONED: ${PHP_EXT_80:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_80:-}
        NODE_VERSION_VERSIONED: ${NODE_VERSION_80:-}
    profiles:
      - phpapache
      - php80apache

  php81apache:
    <<: *apache-php-service
    container_name: PHP_8.1_APACHE
    hostname: php-81-apache
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - "${PROJECT_DIR:-./../../../application}:/app"
      - ../conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ../conf/openssl.cnf:/etc/ssl/openssl.cnf
      - ../../configuration/php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ../../configuration/apache/php81:/etc/apache2/sites-enabled
      - ../../configuration/ssl:/etc/mkcert
      - "../../configuration/ssh:/home/${USER}/.ssh:ro"
      - ../../logs/apache:/var/log/apache2
    build:
      context: ../dockerfiles
      dockerfile: apache.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USER}
        PHP_EXT: ${PHP_EXT:-}
        LINUX_PKG: ${LINUX_PKG:-}
        NODE_VERSION: ${NODE_VERSION:-}
        WORKING_DIR: ${WORKING_DIR}
        PHP_VERSION: 8.1
        PHP_EXT_VERSIONED: ${PHP_EXT_81:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_81:-}
        NODE_VERSION_VERSIONED: ${NODE_VERSION_81:-}
    profiles:
      - phpapache
      - php81apache

  php82apache:
    <<: *apache-php-service
    container_name: PHP_8.2_APACHE
    hostname: php-82-apache
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - "${PROJECT_DIR:-./../../../application}:/app"
      - ../conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ../conf/openssl.cnf:/etc/ssl/openssl.cnf
      - ../../configuration/php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ../../configuration/apache/php82:/etc/apache2/sites-enabled
      - ../../configuration/ssl:/etc/mkcert
      - "../../configuration/ssh:/home/${USER}/.ssh:ro"
      - ../../logs/apache:/var/log/apache2
    build:
      context: ../dockerfiles
      dockerfile: apache.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USER}
        PHP_EXT: ${PHP_EXT:-}
        LINUX_PKG: ${LINUX_PKG:-}
        NODE_VERSION: ${NODE_VERSION:-}
        WORKING_DIR: ${WORKING_DIR}
        PHP_VERSION: 8.2
        PHP_EXT_VERSIONED: ${PHP_EXT_82:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_82:-}
        NODE_VERSION_VERSIONED: ${NODE_VERSION_82:-}
    profiles:
      - phpapache
      - php82apache

  php83apache:
    <<: *apache-php-service
    container_name: PHP_8.3_APACHE
    hostname: php-83-apache
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - "${PROJECT_DIR:-./../../../application}:/app"
      - ../conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ../conf/openssl.cnf:/etc/ssl/openssl.cnf
      - ../../configuration/php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ../../configuration/apache/php83:/etc/apache2/sites-enabled
      - ../../configuration/ssl:/etc/mkcert
      - "../../configuration/ssh:/home/${USER}/.ssh:ro"
      - ../../logs/apache:/var/log/apache2
    build:
      context: ../dockerfiles
      dockerfile: apache.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USER}
        PHP_EXT: ${PHP_EXT:-}
        LINUX_PKG: ${LINUX_PKG:-}
        NODE_VERSION: ${NODE_VERSION:-}
        WORKING_DIR: ${WORKING_DIR}
        PHP_VERSION: 8.3
        PHP_EXT_VERSIONED: ${PHP_EXT_83:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_83:-}
        NODE_VERSION_VERSIONED: ${NODE_VERSION_83:-}
    profiles:
      - phpapache
      - php83apache

  php84apache:
    <<: *apache-php-service
    container_name: PHP_8.4_APACHE
    hostname: php-84-apache
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - "${PROJECT_DIR:-./../../../application}:/app"
      - ../conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ../conf/openssl.cnf:/etc/ssl/openssl.cnf
      - ../../configuration/php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ../../configuration/apache/php84:/etc/apache2/sites-enabled
      - ../../configuration/ssl:/etc/mkcert
      - "../../configuration/ssh:/home/${USER}/.ssh:ro"
      - ../../logs/apache:/var/log/apache2
    build:
      context: ../dockerfiles
      dockerfile: apache.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USER}
        PHP_EXT: ${PHP_EXT:-}
        LINUX_PKG: ${LINUX_PKG:-}
        NODE_VERSION: ${NODE_VERSION:-}
        WORKING_DIR: ${WORKING_DIR}
        PHP_VERSION: 8.4
        PHP_EXT_VERSIONED: ${PHP_EXT_84:-}
        LINUX_PKG_VERSIONED: ${LINUX_PKG_84:-}
        NODE_VERSION_VERSIONED: ${NODE_VERSION_84:-}
    profiles:
      - phpapache
      - php84apache
