services:
  php8.1:
    container_name: PHP_8.1
    build:
      context: docker/conf/docker-files
      dockerfile: fpm.Dockerfile
      args:
        PHP_VERSION: 8.1
        UID: ${UID:-1000}
        GID: ${GID:-root}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS_81:-}
        LINUX_PACKAGES: ${LINUX_PACKAGES_81:-}
        NODE_VERSION: ${NODE_VERSION_81:-}
        WORKING_DIR: ${WORKING_DIR}
#    profiles:
#      - php8.1
    restart: always
    environment:
      - TZ=${TZ:-Asia/Dhaka}
    env_file:
      - "./.env"
    volumes:
      - "${PROJECT_DIR:-./../application}:/app"
      - ./configuration/php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./docker/conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/conf/php/openssl.cnf:/etc/ssl/openssl.cnf
      - ./configuration/ssh:/home/devuser/.ssh
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - frontend
      - backend
  php8.2:
    container_name: PHP_8.2
    build:
      context: docker/conf/docker-files
      dockerfile: fpm.Dockerfile
      args:
        PHP_VERSION: 8.2
        UID: ${UID:-1000}
        GID: ${GID:-root}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS_82:-}
        LINUX_PACKAGES: ${LINUX_PACKAGES_82:-}
        NODE_VERSION: ${NODE_VERSION_82:-}
        WORKING_DIR: ${WORKING_DIR}
#    profiles:
#      - php8.2
    restart: always
    environment:
      - TZ=${TZ:-Asia/Dhaka}
    env_file:
      - "./.env"
    volumes:
      - "${PROJECT_DIR:-./../application}:/app"
      - ./configuration/php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - ./docker/conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/conf/php/openssl.cnf:/etc/ssl/openssl.cnf
      - ./configuration/ssh:/home/devuser/.ssh
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - frontend
      - backend




