x-base-service: &default-service
  environment:
    - TZ=${TZ:-}
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro

services:
  # PostgreSQL Single Instance
  postgres-server:
    <<: *default-service
    container_name: POSTGRESQL
    image: postgres:${POSTGRESQL_VERSION:-latest}
    profiles:
      - postgresql
    restart: always
    ports:
      - "${POSTGRESQL_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DATABASE:-postgres}
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      backend:
        ipv4_address: 172.23.7.1  # Static IP for PostgreSQL Single Instance
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 30s
      timeout: 10s
      retries: 5

  # PostgreSQL Primary (Master) Server
  postgres-master:
    <<: *default-service
    container_name: POSTGRES_MASTER
    image: postgres:${POSTGRESQL_VERSION:-latest}
    profiles:
      - postgresql-replication
    restart: always
    ports:
      - "${POSTGRESQL_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DATABASE:-postgres}
    volumes:
      - ./data/postgresql-master:/var/lib/postgresql/data
      - ./configuration/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf  # Custom config for replication
    networks:
      backend:
        ipv4_address: 172.23.7.2  # Static IP for PostgreSQL Master
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 30s
      timeout: 10s
      retries: 5

  # PostgreSQL Replica (Slave) Server
  postgres-replica:
    <<: *default-service
    container_name: POSTGRES_REPLICA
    image: postgres:${POSTGRESQL_VERSION:-latest}
    profiles:
      - postgresql-replication
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DATABASE:-postgres}
      - REPLICATE_FROM=postgres-master
    volumes:
      - ./data/postgresql-replica:/var/lib/postgresql/data
    networks:
      backend:
        ipv4_address: 172.23.7.3  # Static IP for PostgreSQL Replica
    depends_on:
      - postgres-master
    command: [ "sh", "-c", "
      pg_basebackup -h ${REPLICATE_FROM} -D /var/lib/postgresql/data -U ${POSTGRES_USER} -v -P -R --wal-method=stream &&
      postgres
    " ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 30s
      timeout: 10s
      retries: 5

  # pgAdmin Client
  postgres-client:
    <<: *default-service
    container_name: PG_ADMIN
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "${PGADMIN_PORT:-5400}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@email.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_HOST=postgres-server
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      frontend:
        ipv4_address: 172.22.7.1  # Static IP for pgAdmin on Frontend
      backend:
        ipv4_address: 172.23.7.100  # Static IP for pgAdmin on Backend
    profiles:
      - postgresql-client

  # pgAdmin Client
  postgres-replication-client:
    <<: *default-service
    container_name: PG_REPLICATION_ADMIN
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "${PGADMIN_PORT:-5400}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@email.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_HOST=postgres-master
    volumes:
      - ./data/pgadmin-replication:/var/lib/pgadmin
    networks:
      frontend:
        ipv4_address: 172.22.7.2  # Static IP for pgAdmin on Frontend
      backend:
        ipv4_address: 172.23.7.101  # Static IP for pgAdmin on Backend
    profiles:
      - postgresql-replication-client
