services:
  postgres-server:
    container_name: POSTGRESQL
    image: postgres:${POSTGRESQL_VERSION:-latest}
    profiles:
      - postgresql
    restart: always
    ports:
      - "${POSTGRESQL_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DATABASE:-postgres}
      - TZ=${TZ:-Asia/Dhaka}
    volumes:
      - ./docker/data/postgresql:/var/lib/postgresql/data
    networks:
      - backend
  postgres-client:
    container_name: PG_ADMIN
    image: dpage/pgadmin4:latest
    profiles:
      - postgresql
    restart: always
    ports:
      - "${PGADMIN_PORT:-5400}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - TZ=${TZ:-Asia/Dhaka}
    volumes:
      - ./docker/data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres-server
    networks:
      - frontend
      - backend
