x-base-service: &default-service
  environment:
    - TZ=${TZ:-}
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro

services:
  # Redis Single Instance
  redis-server:
    <<: *default-service
    container_name: REDIS
    hostname: redis
    image: redis/redis-stack-server:${REDIS_VERSION:-latest}
    profiles:
      - redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ./data/redis:/data
    environment:
      - REDIS_ARGS="--save 10 1 --appendonly yes"
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Master (Primary)
  redis-master:
    <<: *default-service
    container_name: REDIS_MASTER
    hostname: redis-master
    image: redis/redis-stack-server:${REDIS_VERSION:-latest}
    profiles:
      - redis-replication
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ./data/redis-master:/data
    environment:
      - REDIS_ARGS="--save 10 1 --appendonly yes"
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Replica (Slave)
  redis-replica:
    <<: *default-service
    container_name: REDIS_REPLICA
    hostname: redis-replica
    image: redis/redis-stack-server:${REDIS_VERSION:-latest}
    profiles:
      - redis-replication
    restart: unless-stopped
    depends_on:
      - redis-master
    environment:
      - REDIS_ARGS="--save 10 1 --appendonly yes"
    command: [ "sh", "-c", "redis-server --replicaof redis-master 6379" ]
    volumes:
      - ./data/redis-replica:/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "redis-master", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # RedisInsight Client
  redis-client:
    <<: *default-service
    container_name: REDIS_INSIGHT
    hostname: redis-insight
    image: redis/redisinsight:latest
    restart: unless-stopped
    environment:
      - REDIS_INSIGHT_REDIS_HOST=redis-server
    ports:
      - "${REDIS_INSIGHT_PORT:-5540}:5540"
    volumes:
      - ./data/redis-insight:/data
    networks:
      - frontend
      - backend
    profiles:
      - redis-client

  # RedisInsight Client
  redis-replication-client:
    <<: *default-service
    container_name: REDIS_REPLICATION_INSIGHT
    hostname: redis-replication-insight
    image: redis/redisinsight:latest
    restart: unless-stopped
    environment:
      - REDIS_INSIGHT_REDIS_HOST=redis-master
    ports:
      - "${REDIS_INSIGHT_PORT:-5540}:5540"
    volumes:
      - ./data/redis-replication-insight:/data
    networks:
      - frontend
      - backend
    profiles:
      - redis-replication-client
